// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: modules/routing/proto/routing.proto

#ifndef PROTOBUF_modules_2frouting_2fproto_2frouting_2eproto__INCLUDED
#define PROTOBUF_modules_2frouting_2fproto_2frouting_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3000000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3000000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
#include "modules/common/proto/header.pb.h"
#include "modules/common/proto/geometry.pb.h"
#include "modules/common/proto/error_code.pb.h"
#include "modules/map/proto/map_parking_space.pb.h"
// @@protoc_insertion_point(includes)

namespace apollo {
namespace routing {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_modules_2frouting_2fproto_2frouting_2eproto();
void protobuf_AssignDesc_modules_2frouting_2fproto_2frouting_2eproto();
void protobuf_ShutdownFile_modules_2frouting_2fproto_2frouting_2eproto();

class LaneSegment;
class LaneWaypoint;
class Measurement;
class ParkingInfo;
class Passage;
class RoadSegment;
class RoutingRequest;
class RoutingResponse;

enum ChangeLaneType {
  FORWARD = 0,
  LEFT = 1,
  RIGHT = 2
};
bool ChangeLaneType_IsValid(int value);
const ChangeLaneType ChangeLaneType_MIN = FORWARD;
const ChangeLaneType ChangeLaneType_MAX = RIGHT;
const int ChangeLaneType_ARRAYSIZE = ChangeLaneType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ChangeLaneType_descriptor();
inline const ::std::string& ChangeLaneType_Name(ChangeLaneType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ChangeLaneType_descriptor(), value);
}
inline bool ChangeLaneType_Parse(
    const ::std::string& name, ChangeLaneType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ChangeLaneType>(
    ChangeLaneType_descriptor(), name, value);
}
// ===================================================================

class LaneWaypoint : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.LaneWaypoint) */ {
 public:
  LaneWaypoint();
  virtual ~LaneWaypoint();

  LaneWaypoint(const LaneWaypoint& from);

  inline LaneWaypoint& operator=(const LaneWaypoint& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LaneWaypoint& default_instance();

  void Swap(LaneWaypoint* other);

  // implements Message ----------------------------------------------

  inline LaneWaypoint* New() const { return New(NULL); }

  LaneWaypoint* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LaneWaypoint& from);
  void MergeFrom(const LaneWaypoint& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LaneWaypoint* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional double s = 2;
  bool has_s() const;
  void clear_s();
  static const int kSFieldNumber = 2;
  double s() const;
  void set_s(double value);

  // optional .apollo.common.PointENU pose = 3;
  bool has_pose() const;
  void clear_pose();
  static const int kPoseFieldNumber = 3;
  const ::apollo::common::PointENU& pose() const;
  ::apollo::common::PointENU* mutable_pose();
  ::apollo::common::PointENU* release_pose();
  void set_allocated_pose(::apollo::common::PointENU* pose);

  // @@protoc_insertion_point(class_scope:apollo.routing.LaneWaypoint)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_s();
  inline void clear_has_s();
  inline void set_has_pose();
  inline void clear_has_pose();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  double s_;
  ::apollo::common::PointENU* pose_;
  friend void  protobuf_AddDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_AssignDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_ShutdownFile_modules_2frouting_2fproto_2frouting_2eproto();

  void InitAsDefaultInstance();
  static LaneWaypoint* default_instance_;
};
// -------------------------------------------------------------------

class LaneSegment : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.LaneSegment) */ {
 public:
  LaneSegment();
  virtual ~LaneSegment();

  LaneSegment(const LaneSegment& from);

  inline LaneSegment& operator=(const LaneSegment& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const LaneSegment& default_instance();

  void Swap(LaneSegment* other);

  // implements Message ----------------------------------------------

  inline LaneSegment* New() const { return New(NULL); }

  LaneSegment* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const LaneSegment& from);
  void MergeFrom(const LaneSegment& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(LaneSegment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // optional double start_s = 2;
  bool has_start_s() const;
  void clear_start_s();
  static const int kStartSFieldNumber = 2;
  double start_s() const;
  void set_start_s(double value);

  // optional double end_s = 3;
  bool has_end_s() const;
  void clear_end_s();
  static const int kEndSFieldNumber = 3;
  double end_s() const;
  void set_end_s(double value);

  // @@protoc_insertion_point(class_scope:apollo.routing.LaneSegment)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_start_s();
  inline void clear_has_start_s();
  inline void set_has_end_s();
  inline void clear_has_end_s();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  double start_s_;
  double end_s_;
  friend void  protobuf_AddDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_AssignDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_ShutdownFile_modules_2frouting_2fproto_2frouting_2eproto();

  void InitAsDefaultInstance();
  static LaneSegment* default_instance_;
};
// -------------------------------------------------------------------

class ParkingInfo : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.ParkingInfo) */ {
 public:
  ParkingInfo();
  virtual ~ParkingInfo();

  ParkingInfo(const ParkingInfo& from);

  inline ParkingInfo& operator=(const ParkingInfo& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ParkingInfo& default_instance();

  void Swap(ParkingInfo* other);

  // implements Message ----------------------------------------------

  inline ParkingInfo* New() const { return New(NULL); }

  ParkingInfo* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ParkingInfo& from);
  void MergeFrom(const ParkingInfo& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(ParkingInfo* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string parking_space_id = 1;
  bool has_parking_space_id() const;
  void clear_parking_space_id();
  static const int kParkingSpaceIdFieldNumber = 1;
  const ::std::string& parking_space_id() const;
  void set_parking_space_id(const ::std::string& value);
  void set_parking_space_id(const char* value);
  void set_parking_space_id(const char* value, size_t size);
  ::std::string* mutable_parking_space_id();
  ::std::string* release_parking_space_id();
  void set_allocated_parking_space_id(::std::string* parking_space_id);

  // optional .apollo.common.PointENU parking_point = 2;
  bool has_parking_point() const;
  void clear_parking_point();
  static const int kParkingPointFieldNumber = 2;
  const ::apollo::common::PointENU& parking_point() const;
  ::apollo::common::PointENU* mutable_parking_point();
  ::apollo::common::PointENU* release_parking_point();
  void set_allocated_parking_point(::apollo::common::PointENU* parking_point);

  // @@protoc_insertion_point(class_scope:apollo.routing.ParkingInfo)
 private:
  inline void set_has_parking_space_id();
  inline void clear_has_parking_space_id();
  inline void set_has_parking_point();
  inline void clear_has_parking_point();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr parking_space_id_;
  ::apollo::common::PointENU* parking_point_;
  friend void  protobuf_AddDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_AssignDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_ShutdownFile_modules_2frouting_2fproto_2frouting_2eproto();

  void InitAsDefaultInstance();
  static ParkingInfo* default_instance_;
};
// -------------------------------------------------------------------

class RoutingRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.RoutingRequest) */ {
 public:
  RoutingRequest();
  virtual ~RoutingRequest();

  RoutingRequest(const RoutingRequest& from);

  inline RoutingRequest& operator=(const RoutingRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoutingRequest& default_instance();

  void Swap(RoutingRequest* other);

  // implements Message ----------------------------------------------

  inline RoutingRequest* New() const { return New(NULL); }

  RoutingRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RoutingRequest& from);
  void MergeFrom(const RoutingRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RoutingRequest* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.common.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* mutable_header();
  ::apollo::common::Header* release_header();
  void set_allocated_header(::apollo::common::Header* header);

  // repeated .apollo.routing.LaneWaypoint waypoint = 2;
  int waypoint_size() const;
  void clear_waypoint();
  static const int kWaypointFieldNumber = 2;
  const ::apollo::routing::LaneWaypoint& waypoint(int index) const;
  ::apollo::routing::LaneWaypoint* mutable_waypoint(int index);
  ::apollo::routing::LaneWaypoint* add_waypoint();
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneWaypoint >*
      mutable_waypoint();
  const ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneWaypoint >&
      waypoint() const;

  // repeated .apollo.routing.LaneSegment blacklisted_lane = 3;
  int blacklisted_lane_size() const;
  void clear_blacklisted_lane();
  static const int kBlacklistedLaneFieldNumber = 3;
  const ::apollo::routing::LaneSegment& blacklisted_lane(int index) const;
  ::apollo::routing::LaneSegment* mutable_blacklisted_lane(int index);
  ::apollo::routing::LaneSegment* add_blacklisted_lane();
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >*
      mutable_blacklisted_lane();
  const ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >&
      blacklisted_lane() const;

  // repeated string blacklisted_road = 4;
  int blacklisted_road_size() const;
  void clear_blacklisted_road();
  static const int kBlacklistedRoadFieldNumber = 4;
  const ::std::string& blacklisted_road(int index) const;
  ::std::string* mutable_blacklisted_road(int index);
  void set_blacklisted_road(int index, const ::std::string& value);
  void set_blacklisted_road(int index, const char* value);
  void set_blacklisted_road(int index, const char* value, size_t size);
  ::std::string* add_blacklisted_road();
  void add_blacklisted_road(const ::std::string& value);
  void add_blacklisted_road(const char* value);
  void add_blacklisted_road(const char* value, size_t size);
  const ::google::protobuf::RepeatedPtrField< ::std::string>& blacklisted_road() const;
  ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_blacklisted_road();

  // optional bool broadcast = 5 [default = true];
  bool has_broadcast() const;
  void clear_broadcast();
  static const int kBroadcastFieldNumber = 5;
  bool broadcast() const;
  void set_broadcast(bool value);

  // optional .apollo.hdmap.ParkingSpace parking_space = 6 [deprecated = true];
  GOOGLE_PROTOBUF_DEPRECATED_ATTR bool has_parking_space() const;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR void clear_parking_space();
  GOOGLE_PROTOBUF_DEPRECATED_ATTR static const int kParkingSpaceFieldNumber = 6;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR const ::apollo::hdmap::ParkingSpace& parking_space() const;
  GOOGLE_PROTOBUF_DEPRECATED_ATTR ::apollo::hdmap::ParkingSpace* mutable_parking_space();
  GOOGLE_PROTOBUF_DEPRECATED_ATTR ::apollo::hdmap::ParkingSpace* release_parking_space();
  GOOGLE_PROTOBUF_DEPRECATED_ATTR void set_allocated_parking_space(::apollo::hdmap::ParkingSpace* parking_space);

  // optional .apollo.routing.ParkingInfo parking_info = 7;
  bool has_parking_info() const;
  void clear_parking_info();
  static const int kParkingInfoFieldNumber = 7;
  const ::apollo::routing::ParkingInfo& parking_info() const;
  ::apollo::routing::ParkingInfo* mutable_parking_info();
  ::apollo::routing::ParkingInfo* release_parking_info();
  void set_allocated_parking_info(::apollo::routing::ParkingInfo* parking_info);

  // @@protoc_insertion_point(class_scope:apollo.routing.RoutingRequest)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_broadcast();
  inline void clear_has_broadcast();
  inline void set_has_parking_space();
  inline void clear_has_parking_space();
  inline void set_has_parking_info();
  inline void clear_has_parking_info();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::apollo::common::Header* header_;
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneWaypoint > waypoint_;
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment > blacklisted_lane_;
  ::google::protobuf::RepeatedPtrField< ::std::string> blacklisted_road_;
  ::apollo::hdmap::ParkingSpace* parking_space_;
  ::apollo::routing::ParkingInfo* parking_info_;
  bool broadcast_;
  friend void  protobuf_AddDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_AssignDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_ShutdownFile_modules_2frouting_2fproto_2frouting_2eproto();

  void InitAsDefaultInstance();
  static RoutingRequest* default_instance_;
};
// -------------------------------------------------------------------

class Measurement : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.Measurement) */ {
 public:
  Measurement();
  virtual ~Measurement();

  Measurement(const Measurement& from);

  inline Measurement& operator=(const Measurement& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Measurement& default_instance();

  void Swap(Measurement* other);

  // implements Message ----------------------------------------------

  inline Measurement* New() const { return New(NULL); }

  Measurement* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Measurement& from);
  void MergeFrom(const Measurement& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Measurement* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional double distance = 1;
  bool has_distance() const;
  void clear_distance();
  static const int kDistanceFieldNumber = 1;
  double distance() const;
  void set_distance(double value);

  // @@protoc_insertion_point(class_scope:apollo.routing.Measurement)
 private:
  inline void set_has_distance();
  inline void clear_has_distance();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  double distance_;
  friend void  protobuf_AddDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_AssignDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_ShutdownFile_modules_2frouting_2fproto_2frouting_2eproto();

  void InitAsDefaultInstance();
  static Measurement* default_instance_;
};
// -------------------------------------------------------------------

class Passage : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.Passage) */ {
 public:
  Passage();
  virtual ~Passage();

  Passage(const Passage& from);

  inline Passage& operator=(const Passage& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Passage& default_instance();

  void Swap(Passage* other);

  // implements Message ----------------------------------------------

  inline Passage* New() const { return New(NULL); }

  Passage* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Passage& from);
  void MergeFrom(const Passage& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Passage* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .apollo.routing.LaneSegment segment = 1;
  int segment_size() const;
  void clear_segment();
  static const int kSegmentFieldNumber = 1;
  const ::apollo::routing::LaneSegment& segment(int index) const;
  ::apollo::routing::LaneSegment* mutable_segment(int index);
  ::apollo::routing::LaneSegment* add_segment();
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >*
      mutable_segment();
  const ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >&
      segment() const;

  // optional bool can_exit = 2;
  bool has_can_exit() const;
  void clear_can_exit();
  static const int kCanExitFieldNumber = 2;
  bool can_exit() const;
  void set_can_exit(bool value);

  // optional .apollo.routing.ChangeLaneType change_lane_type = 3 [default = FORWARD];
  bool has_change_lane_type() const;
  void clear_change_lane_type();
  static const int kChangeLaneTypeFieldNumber = 3;
  ::apollo::routing::ChangeLaneType change_lane_type() const;
  void set_change_lane_type(::apollo::routing::ChangeLaneType value);

  // @@protoc_insertion_point(class_scope:apollo.routing.Passage)
 private:
  inline void set_has_can_exit();
  inline void clear_has_can_exit();
  inline void set_has_change_lane_type();
  inline void clear_has_change_lane_type();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment > segment_;
  bool can_exit_;
  int change_lane_type_;
  friend void  protobuf_AddDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_AssignDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_ShutdownFile_modules_2frouting_2fproto_2frouting_2eproto();

  void InitAsDefaultInstance();
  static Passage* default_instance_;
};
// -------------------------------------------------------------------

class RoadSegment : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.RoadSegment) */ {
 public:
  RoadSegment();
  virtual ~RoadSegment();

  RoadSegment(const RoadSegment& from);

  inline RoadSegment& operator=(const RoadSegment& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoadSegment& default_instance();

  void Swap(RoadSegment* other);

  // implements Message ----------------------------------------------

  inline RoadSegment* New() const { return New(NULL); }

  RoadSegment* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RoadSegment& from);
  void MergeFrom(const RoadSegment& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RoadSegment* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string id = 1;
  bool has_id() const;
  void clear_id();
  static const int kIdFieldNumber = 1;
  const ::std::string& id() const;
  void set_id(const ::std::string& value);
  void set_id(const char* value);
  void set_id(const char* value, size_t size);
  ::std::string* mutable_id();
  ::std::string* release_id();
  void set_allocated_id(::std::string* id);

  // repeated .apollo.routing.Passage passage = 2;
  int passage_size() const;
  void clear_passage();
  static const int kPassageFieldNumber = 2;
  const ::apollo::routing::Passage& passage(int index) const;
  ::apollo::routing::Passage* mutable_passage(int index);
  ::apollo::routing::Passage* add_passage();
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::Passage >*
      mutable_passage();
  const ::google::protobuf::RepeatedPtrField< ::apollo::routing::Passage >&
      passage() const;

  // @@protoc_insertion_point(class_scope:apollo.routing.RoadSegment)
 private:
  inline void set_has_id();
  inline void clear_has_id();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr id_;
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::Passage > passage_;
  friend void  protobuf_AddDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_AssignDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_ShutdownFile_modules_2frouting_2fproto_2frouting_2eproto();

  void InitAsDefaultInstance();
  static RoadSegment* default_instance_;
};
// -------------------------------------------------------------------

class RoutingResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:apollo.routing.RoutingResponse) */ {
 public:
  RoutingResponse();
  virtual ~RoutingResponse();

  RoutingResponse(const RoutingResponse& from);

  inline RoutingResponse& operator=(const RoutingResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RoutingResponse& default_instance();

  void Swap(RoutingResponse* other);

  // implements Message ----------------------------------------------

  inline RoutingResponse* New() const { return New(NULL); }

  RoutingResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RoutingResponse& from);
  void MergeFrom(const RoutingResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RoutingResponse* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .apollo.common.Header header = 1;
  bool has_header() const;
  void clear_header();
  static const int kHeaderFieldNumber = 1;
  const ::apollo::common::Header& header() const;
  ::apollo::common::Header* mutable_header();
  ::apollo::common::Header* release_header();
  void set_allocated_header(::apollo::common::Header* header);

  // repeated .apollo.routing.RoadSegment road = 2;
  int road_size() const;
  void clear_road();
  static const int kRoadFieldNumber = 2;
  const ::apollo::routing::RoadSegment& road(int index) const;
  ::apollo::routing::RoadSegment* mutable_road(int index);
  ::apollo::routing::RoadSegment* add_road();
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::RoadSegment >*
      mutable_road();
  const ::google::protobuf::RepeatedPtrField< ::apollo::routing::RoadSegment >&
      road() const;

  // optional .apollo.routing.Measurement measurement = 3;
  bool has_measurement() const;
  void clear_measurement();
  static const int kMeasurementFieldNumber = 3;
  const ::apollo::routing::Measurement& measurement() const;
  ::apollo::routing::Measurement* mutable_measurement();
  ::apollo::routing::Measurement* release_measurement();
  void set_allocated_measurement(::apollo::routing::Measurement* measurement);

  // optional .apollo.routing.RoutingRequest routing_request = 4;
  bool has_routing_request() const;
  void clear_routing_request();
  static const int kRoutingRequestFieldNumber = 4;
  const ::apollo::routing::RoutingRequest& routing_request() const;
  ::apollo::routing::RoutingRequest* mutable_routing_request();
  ::apollo::routing::RoutingRequest* release_routing_request();
  void set_allocated_routing_request(::apollo::routing::RoutingRequest* routing_request);

  // optional bytes map_version = 5;
  bool has_map_version() const;
  void clear_map_version();
  static const int kMapVersionFieldNumber = 5;
  const ::std::string& map_version() const;
  void set_map_version(const ::std::string& value);
  void set_map_version(const char* value);
  void set_map_version(const void* value, size_t size);
  ::std::string* mutable_map_version();
  ::std::string* release_map_version();
  void set_allocated_map_version(::std::string* map_version);

  // optional .apollo.common.StatusPb status = 6;
  bool has_status() const;
  void clear_status();
  static const int kStatusFieldNumber = 6;
  const ::apollo::common::StatusPb& status() const;
  ::apollo::common::StatusPb* mutable_status();
  ::apollo::common::StatusPb* release_status();
  void set_allocated_status(::apollo::common::StatusPb* status);

  // @@protoc_insertion_point(class_scope:apollo.routing.RoutingResponse)
 private:
  inline void set_has_header();
  inline void clear_has_header();
  inline void set_has_measurement();
  inline void clear_has_measurement();
  inline void set_has_routing_request();
  inline void clear_has_routing_request();
  inline void set_has_map_version();
  inline void clear_has_map_version();
  inline void set_has_status();
  inline void clear_has_status();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::apollo::common::Header* header_;
  ::google::protobuf::RepeatedPtrField< ::apollo::routing::RoadSegment > road_;
  ::apollo::routing::Measurement* measurement_;
  ::apollo::routing::RoutingRequest* routing_request_;
  ::google::protobuf::internal::ArenaStringPtr map_version_;
  ::apollo::common::StatusPb* status_;
  friend void  protobuf_AddDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_AssignDesc_modules_2frouting_2fproto_2frouting_2eproto();
  friend void protobuf_ShutdownFile_modules_2frouting_2fproto_2frouting_2eproto();

  void InitAsDefaultInstance();
  static RoutingResponse* default_instance_;
};
// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// LaneWaypoint

// optional string id = 1;
inline bool LaneWaypoint::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LaneWaypoint::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LaneWaypoint::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LaneWaypoint::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& LaneWaypoint::id() const {
  // @@protoc_insertion_point(field_get:apollo.routing.LaneWaypoint.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LaneWaypoint::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.routing.LaneWaypoint.id)
}
inline void LaneWaypoint::set_id(const char* value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.routing.LaneWaypoint.id)
}
inline void LaneWaypoint::set_id(const char* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.LaneWaypoint.id)
}
inline ::std::string* LaneWaypoint::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:apollo.routing.LaneWaypoint.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LaneWaypoint::release_id() {
  // @@protoc_insertion_point(field_release:apollo.routing.LaneWaypoint.id)
  clear_has_id();
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LaneWaypoint::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.LaneWaypoint.id)
}

// optional double s = 2;
inline bool LaneWaypoint::has_s() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LaneWaypoint::set_has_s() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LaneWaypoint::clear_has_s() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LaneWaypoint::clear_s() {
  s_ = 0;
  clear_has_s();
}
inline double LaneWaypoint::s() const {
  // @@protoc_insertion_point(field_get:apollo.routing.LaneWaypoint.s)
  return s_;
}
inline void LaneWaypoint::set_s(double value) {
  set_has_s();
  s_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.LaneWaypoint.s)
}

// optional .apollo.common.PointENU pose = 3;
inline bool LaneWaypoint::has_pose() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LaneWaypoint::set_has_pose() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LaneWaypoint::clear_has_pose() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LaneWaypoint::clear_pose() {
  if (pose_ != NULL) pose_->::apollo::common::PointENU::Clear();
  clear_has_pose();
}
inline const ::apollo::common::PointENU& LaneWaypoint::pose() const {
  // @@protoc_insertion_point(field_get:apollo.routing.LaneWaypoint.pose)
  return pose_ != NULL ? *pose_ : *default_instance_->pose_;
}
inline ::apollo::common::PointENU* LaneWaypoint::mutable_pose() {
  set_has_pose();
  if (pose_ == NULL) {
    pose_ = new ::apollo::common::PointENU;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.LaneWaypoint.pose)
  return pose_;
}
inline ::apollo::common::PointENU* LaneWaypoint::release_pose() {
  // @@protoc_insertion_point(field_release:apollo.routing.LaneWaypoint.pose)
  clear_has_pose();
  ::apollo::common::PointENU* temp = pose_;
  pose_ = NULL;
  return temp;
}
inline void LaneWaypoint::set_allocated_pose(::apollo::common::PointENU* pose) {
  delete pose_;
  pose_ = pose;
  if (pose) {
    set_has_pose();
  } else {
    clear_has_pose();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.LaneWaypoint.pose)
}

// -------------------------------------------------------------------

// LaneSegment

// optional string id = 1;
inline bool LaneSegment::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void LaneSegment::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void LaneSegment::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void LaneSegment::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& LaneSegment::id() const {
  // @@protoc_insertion_point(field_get:apollo.routing.LaneSegment.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LaneSegment::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.routing.LaneSegment.id)
}
inline void LaneSegment::set_id(const char* value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.routing.LaneSegment.id)
}
inline void LaneSegment::set_id(const char* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.LaneSegment.id)
}
inline ::std::string* LaneSegment::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:apollo.routing.LaneSegment.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* LaneSegment::release_id() {
  // @@protoc_insertion_point(field_release:apollo.routing.LaneSegment.id)
  clear_has_id();
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void LaneSegment::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.LaneSegment.id)
}

// optional double start_s = 2;
inline bool LaneSegment::has_start_s() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void LaneSegment::set_has_start_s() {
  _has_bits_[0] |= 0x00000002u;
}
inline void LaneSegment::clear_has_start_s() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void LaneSegment::clear_start_s() {
  start_s_ = 0;
  clear_has_start_s();
}
inline double LaneSegment::start_s() const {
  // @@protoc_insertion_point(field_get:apollo.routing.LaneSegment.start_s)
  return start_s_;
}
inline void LaneSegment::set_start_s(double value) {
  set_has_start_s();
  start_s_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.LaneSegment.start_s)
}

// optional double end_s = 3;
inline bool LaneSegment::has_end_s() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void LaneSegment::set_has_end_s() {
  _has_bits_[0] |= 0x00000004u;
}
inline void LaneSegment::clear_has_end_s() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void LaneSegment::clear_end_s() {
  end_s_ = 0;
  clear_has_end_s();
}
inline double LaneSegment::end_s() const {
  // @@protoc_insertion_point(field_get:apollo.routing.LaneSegment.end_s)
  return end_s_;
}
inline void LaneSegment::set_end_s(double value) {
  set_has_end_s();
  end_s_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.LaneSegment.end_s)
}

// -------------------------------------------------------------------

// ParkingInfo

// optional string parking_space_id = 1;
inline bool ParkingInfo::has_parking_space_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ParkingInfo::set_has_parking_space_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ParkingInfo::clear_has_parking_space_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ParkingInfo::clear_parking_space_id() {
  parking_space_id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_parking_space_id();
}
inline const ::std::string& ParkingInfo::parking_space_id() const {
  // @@protoc_insertion_point(field_get:apollo.routing.ParkingInfo.parking_space_id)
  return parking_space_id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ParkingInfo::set_parking_space_id(const ::std::string& value) {
  set_has_parking_space_id();
  parking_space_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.routing.ParkingInfo.parking_space_id)
}
inline void ParkingInfo::set_parking_space_id(const char* value) {
  set_has_parking_space_id();
  parking_space_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.routing.ParkingInfo.parking_space_id)
}
inline void ParkingInfo::set_parking_space_id(const char* value, size_t size) {
  set_has_parking_space_id();
  parking_space_id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.ParkingInfo.parking_space_id)
}
inline ::std::string* ParkingInfo::mutable_parking_space_id() {
  set_has_parking_space_id();
  // @@protoc_insertion_point(field_mutable:apollo.routing.ParkingInfo.parking_space_id)
  return parking_space_id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* ParkingInfo::release_parking_space_id() {
  // @@protoc_insertion_point(field_release:apollo.routing.ParkingInfo.parking_space_id)
  clear_has_parking_space_id();
  return parking_space_id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void ParkingInfo::set_allocated_parking_space_id(::std::string* parking_space_id) {
  if (parking_space_id != NULL) {
    set_has_parking_space_id();
  } else {
    clear_has_parking_space_id();
  }
  parking_space_id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), parking_space_id);
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.ParkingInfo.parking_space_id)
}

// optional .apollo.common.PointENU parking_point = 2;
inline bool ParkingInfo::has_parking_point() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ParkingInfo::set_has_parking_point() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ParkingInfo::clear_has_parking_point() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ParkingInfo::clear_parking_point() {
  if (parking_point_ != NULL) parking_point_->::apollo::common::PointENU::Clear();
  clear_has_parking_point();
}
inline const ::apollo::common::PointENU& ParkingInfo::parking_point() const {
  // @@protoc_insertion_point(field_get:apollo.routing.ParkingInfo.parking_point)
  return parking_point_ != NULL ? *parking_point_ : *default_instance_->parking_point_;
}
inline ::apollo::common::PointENU* ParkingInfo::mutable_parking_point() {
  set_has_parking_point();
  if (parking_point_ == NULL) {
    parking_point_ = new ::apollo::common::PointENU;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.ParkingInfo.parking_point)
  return parking_point_;
}
inline ::apollo::common::PointENU* ParkingInfo::release_parking_point() {
  // @@protoc_insertion_point(field_release:apollo.routing.ParkingInfo.parking_point)
  clear_has_parking_point();
  ::apollo::common::PointENU* temp = parking_point_;
  parking_point_ = NULL;
  return temp;
}
inline void ParkingInfo::set_allocated_parking_point(::apollo::common::PointENU* parking_point) {
  delete parking_point_;
  parking_point_ = parking_point;
  if (parking_point) {
    set_has_parking_point();
  } else {
    clear_has_parking_point();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.ParkingInfo.parking_point)
}

// -------------------------------------------------------------------

// RoutingRequest

// optional .apollo.common.Header header = 1;
inline bool RoutingRequest::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RoutingRequest::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RoutingRequest::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RoutingRequest::clear_header() {
  if (header_ != NULL) header_->::apollo::common::Header::Clear();
  clear_has_header();
}
inline const ::apollo::common::Header& RoutingRequest::header() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::apollo::common::Header* RoutingRequest::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::apollo::common::Header;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingRequest.header)
  return header_;
}
inline ::apollo::common::Header* RoutingRequest::release_header() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingRequest.header)
  clear_has_header();
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void RoutingRequest::set_allocated_header(::apollo::common::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingRequest.header)
}

// repeated .apollo.routing.LaneWaypoint waypoint = 2;
inline int RoutingRequest::waypoint_size() const {
  return waypoint_.size();
}
inline void RoutingRequest::clear_waypoint() {
  waypoint_.Clear();
}
inline const ::apollo::routing::LaneWaypoint& RoutingRequest::waypoint(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.waypoint)
  return waypoint_.Get(index);
}
inline ::apollo::routing::LaneWaypoint* RoutingRequest::mutable_waypoint(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingRequest.waypoint)
  return waypoint_.Mutable(index);
}
inline ::apollo::routing::LaneWaypoint* RoutingRequest::add_waypoint() {
  // @@protoc_insertion_point(field_add:apollo.routing.RoutingRequest.waypoint)
  return waypoint_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneWaypoint >*
RoutingRequest::mutable_waypoint() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.RoutingRequest.waypoint)
  return &waypoint_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneWaypoint >&
RoutingRequest::waypoint() const {
  // @@protoc_insertion_point(field_list:apollo.routing.RoutingRequest.waypoint)
  return waypoint_;
}

// repeated .apollo.routing.LaneSegment blacklisted_lane = 3;
inline int RoutingRequest::blacklisted_lane_size() const {
  return blacklisted_lane_.size();
}
inline void RoutingRequest::clear_blacklisted_lane() {
  blacklisted_lane_.Clear();
}
inline const ::apollo::routing::LaneSegment& RoutingRequest::blacklisted_lane(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.blacklisted_lane)
  return blacklisted_lane_.Get(index);
}
inline ::apollo::routing::LaneSegment* RoutingRequest::mutable_blacklisted_lane(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingRequest.blacklisted_lane)
  return blacklisted_lane_.Mutable(index);
}
inline ::apollo::routing::LaneSegment* RoutingRequest::add_blacklisted_lane() {
  // @@protoc_insertion_point(field_add:apollo.routing.RoutingRequest.blacklisted_lane)
  return blacklisted_lane_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >*
RoutingRequest::mutable_blacklisted_lane() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.RoutingRequest.blacklisted_lane)
  return &blacklisted_lane_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >&
RoutingRequest::blacklisted_lane() const {
  // @@protoc_insertion_point(field_list:apollo.routing.RoutingRequest.blacklisted_lane)
  return blacklisted_lane_;
}

// repeated string blacklisted_road = 4;
inline int RoutingRequest::blacklisted_road_size() const {
  return blacklisted_road_.size();
}
inline void RoutingRequest::clear_blacklisted_road() {
  blacklisted_road_.Clear();
}
inline const ::std::string& RoutingRequest::blacklisted_road(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.blacklisted_road)
  return blacklisted_road_.Get(index);
}
inline ::std::string* RoutingRequest::mutable_blacklisted_road(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingRequest.blacklisted_road)
  return blacklisted_road_.Mutable(index);
}
inline void RoutingRequest::set_blacklisted_road(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:apollo.routing.RoutingRequest.blacklisted_road)
  blacklisted_road_.Mutable(index)->assign(value);
}
inline void RoutingRequest::set_blacklisted_road(int index, const char* value) {
  blacklisted_road_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:apollo.routing.RoutingRequest.blacklisted_road)
}
inline void RoutingRequest::set_blacklisted_road(int index, const char* value, size_t size) {
  blacklisted_road_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.RoutingRequest.blacklisted_road)
}
inline ::std::string* RoutingRequest::add_blacklisted_road() {
  // @@protoc_insertion_point(field_add_mutable:apollo.routing.RoutingRequest.blacklisted_road)
  return blacklisted_road_.Add();
}
inline void RoutingRequest::add_blacklisted_road(const ::std::string& value) {
  blacklisted_road_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:apollo.routing.RoutingRequest.blacklisted_road)
}
inline void RoutingRequest::add_blacklisted_road(const char* value) {
  blacklisted_road_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:apollo.routing.RoutingRequest.blacklisted_road)
}
inline void RoutingRequest::add_blacklisted_road(const char* value, size_t size) {
  blacklisted_road_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:apollo.routing.RoutingRequest.blacklisted_road)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
RoutingRequest::blacklisted_road() const {
  // @@protoc_insertion_point(field_list:apollo.routing.RoutingRequest.blacklisted_road)
  return blacklisted_road_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
RoutingRequest::mutable_blacklisted_road() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.RoutingRequest.blacklisted_road)
  return &blacklisted_road_;
}

// optional bool broadcast = 5 [default = true];
inline bool RoutingRequest::has_broadcast() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RoutingRequest::set_has_broadcast() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RoutingRequest::clear_has_broadcast() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RoutingRequest::clear_broadcast() {
  broadcast_ = true;
  clear_has_broadcast();
}
inline bool RoutingRequest::broadcast() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.broadcast)
  return broadcast_;
}
inline void RoutingRequest::set_broadcast(bool value) {
  set_has_broadcast();
  broadcast_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.RoutingRequest.broadcast)
}

// optional .apollo.hdmap.ParkingSpace parking_space = 6 [deprecated = true];
inline bool RoutingRequest::has_parking_space() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RoutingRequest::set_has_parking_space() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RoutingRequest::clear_has_parking_space() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RoutingRequest::clear_parking_space() {
  if (parking_space_ != NULL) parking_space_->::apollo::hdmap::ParkingSpace::Clear();
  clear_has_parking_space();
}
inline const ::apollo::hdmap::ParkingSpace& RoutingRequest::parking_space() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.parking_space)
  return parking_space_ != NULL ? *parking_space_ : *default_instance_->parking_space_;
}
inline ::apollo::hdmap::ParkingSpace* RoutingRequest::mutable_parking_space() {
  set_has_parking_space();
  if (parking_space_ == NULL) {
    parking_space_ = new ::apollo::hdmap::ParkingSpace;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingRequest.parking_space)
  return parking_space_;
}
inline ::apollo::hdmap::ParkingSpace* RoutingRequest::release_parking_space() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingRequest.parking_space)
  clear_has_parking_space();
  ::apollo::hdmap::ParkingSpace* temp = parking_space_;
  parking_space_ = NULL;
  return temp;
}
inline void RoutingRequest::set_allocated_parking_space(::apollo::hdmap::ParkingSpace* parking_space) {
  delete parking_space_;
  parking_space_ = parking_space;
  if (parking_space) {
    set_has_parking_space();
  } else {
    clear_has_parking_space();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingRequest.parking_space)
}

// optional .apollo.routing.ParkingInfo parking_info = 7;
inline bool RoutingRequest::has_parking_info() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void RoutingRequest::set_has_parking_info() {
  _has_bits_[0] |= 0x00000040u;
}
inline void RoutingRequest::clear_has_parking_info() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void RoutingRequest::clear_parking_info() {
  if (parking_info_ != NULL) parking_info_->::apollo::routing::ParkingInfo::Clear();
  clear_has_parking_info();
}
inline const ::apollo::routing::ParkingInfo& RoutingRequest::parking_info() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingRequest.parking_info)
  return parking_info_ != NULL ? *parking_info_ : *default_instance_->parking_info_;
}
inline ::apollo::routing::ParkingInfo* RoutingRequest::mutable_parking_info() {
  set_has_parking_info();
  if (parking_info_ == NULL) {
    parking_info_ = new ::apollo::routing::ParkingInfo;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingRequest.parking_info)
  return parking_info_;
}
inline ::apollo::routing::ParkingInfo* RoutingRequest::release_parking_info() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingRequest.parking_info)
  clear_has_parking_info();
  ::apollo::routing::ParkingInfo* temp = parking_info_;
  parking_info_ = NULL;
  return temp;
}
inline void RoutingRequest::set_allocated_parking_info(::apollo::routing::ParkingInfo* parking_info) {
  delete parking_info_;
  parking_info_ = parking_info;
  if (parking_info) {
    set_has_parking_info();
  } else {
    clear_has_parking_info();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingRequest.parking_info)
}

// -------------------------------------------------------------------

// Measurement

// optional double distance = 1;
inline bool Measurement::has_distance() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Measurement::set_has_distance() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Measurement::clear_has_distance() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Measurement::clear_distance() {
  distance_ = 0;
  clear_has_distance();
}
inline double Measurement::distance() const {
  // @@protoc_insertion_point(field_get:apollo.routing.Measurement.distance)
  return distance_;
}
inline void Measurement::set_distance(double value) {
  set_has_distance();
  distance_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.Measurement.distance)
}

// -------------------------------------------------------------------

// Passage

// repeated .apollo.routing.LaneSegment segment = 1;
inline int Passage::segment_size() const {
  return segment_.size();
}
inline void Passage::clear_segment() {
  segment_.Clear();
}
inline const ::apollo::routing::LaneSegment& Passage::segment(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.Passage.segment)
  return segment_.Get(index);
}
inline ::apollo::routing::LaneSegment* Passage::mutable_segment(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.Passage.segment)
  return segment_.Mutable(index);
}
inline ::apollo::routing::LaneSegment* Passage::add_segment() {
  // @@protoc_insertion_point(field_add:apollo.routing.Passage.segment)
  return segment_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >*
Passage::mutable_segment() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.Passage.segment)
  return &segment_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::routing::LaneSegment >&
Passage::segment() const {
  // @@protoc_insertion_point(field_list:apollo.routing.Passage.segment)
  return segment_;
}

// optional bool can_exit = 2;
inline bool Passage::has_can_exit() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Passage::set_has_can_exit() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Passage::clear_has_can_exit() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Passage::clear_can_exit() {
  can_exit_ = false;
  clear_has_can_exit();
}
inline bool Passage::can_exit() const {
  // @@protoc_insertion_point(field_get:apollo.routing.Passage.can_exit)
  return can_exit_;
}
inline void Passage::set_can_exit(bool value) {
  set_has_can_exit();
  can_exit_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.Passage.can_exit)
}

// optional .apollo.routing.ChangeLaneType change_lane_type = 3 [default = FORWARD];
inline bool Passage::has_change_lane_type() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Passage::set_has_change_lane_type() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Passage::clear_has_change_lane_type() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Passage::clear_change_lane_type() {
  change_lane_type_ = 0;
  clear_has_change_lane_type();
}
inline ::apollo::routing::ChangeLaneType Passage::change_lane_type() const {
  // @@protoc_insertion_point(field_get:apollo.routing.Passage.change_lane_type)
  return static_cast< ::apollo::routing::ChangeLaneType >(change_lane_type_);
}
inline void Passage::set_change_lane_type(::apollo::routing::ChangeLaneType value) {
  assert(::apollo::routing::ChangeLaneType_IsValid(value));
  set_has_change_lane_type();
  change_lane_type_ = value;
  // @@protoc_insertion_point(field_set:apollo.routing.Passage.change_lane_type)
}

// -------------------------------------------------------------------

// RoadSegment

// optional string id = 1;
inline bool RoadSegment::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RoadSegment::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RoadSegment::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RoadSegment::clear_id() {
  id_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_id();
}
inline const ::std::string& RoadSegment::id() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoadSegment.id)
  return id_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoadSegment::set_id(const ::std::string& value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.routing.RoadSegment.id)
}
inline void RoadSegment::set_id(const char* value) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.routing.RoadSegment.id)
}
inline void RoadSegment::set_id(const char* value, size_t size) {
  set_has_id();
  id_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.RoadSegment.id)
}
inline ::std::string* RoadSegment::mutable_id() {
  set_has_id();
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoadSegment.id)
  return id_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoadSegment::release_id() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoadSegment.id)
  clear_has_id();
  return id_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoadSegment::set_allocated_id(::std::string* id) {
  if (id != NULL) {
    set_has_id();
  } else {
    clear_has_id();
  }
  id_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), id);
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoadSegment.id)
}

// repeated .apollo.routing.Passage passage = 2;
inline int RoadSegment::passage_size() const {
  return passage_.size();
}
inline void RoadSegment::clear_passage() {
  passage_.Clear();
}
inline const ::apollo::routing::Passage& RoadSegment::passage(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoadSegment.passage)
  return passage_.Get(index);
}
inline ::apollo::routing::Passage* RoadSegment::mutable_passage(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoadSegment.passage)
  return passage_.Mutable(index);
}
inline ::apollo::routing::Passage* RoadSegment::add_passage() {
  // @@protoc_insertion_point(field_add:apollo.routing.RoadSegment.passage)
  return passage_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::routing::Passage >*
RoadSegment::mutable_passage() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.RoadSegment.passage)
  return &passage_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::routing::Passage >&
RoadSegment::passage() const {
  // @@protoc_insertion_point(field_list:apollo.routing.RoadSegment.passage)
  return passage_;
}

// -------------------------------------------------------------------

// RoutingResponse

// optional .apollo.common.Header header = 1;
inline bool RoutingResponse::has_header() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RoutingResponse::set_has_header() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RoutingResponse::clear_has_header() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RoutingResponse::clear_header() {
  if (header_ != NULL) header_->::apollo::common::Header::Clear();
  clear_has_header();
}
inline const ::apollo::common::Header& RoutingResponse::header() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingResponse.header)
  return header_ != NULL ? *header_ : *default_instance_->header_;
}
inline ::apollo::common::Header* RoutingResponse::mutable_header() {
  set_has_header();
  if (header_ == NULL) {
    header_ = new ::apollo::common::Header;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingResponse.header)
  return header_;
}
inline ::apollo::common::Header* RoutingResponse::release_header() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingResponse.header)
  clear_has_header();
  ::apollo::common::Header* temp = header_;
  header_ = NULL;
  return temp;
}
inline void RoutingResponse::set_allocated_header(::apollo::common::Header* header) {
  delete header_;
  header_ = header;
  if (header) {
    set_has_header();
  } else {
    clear_has_header();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingResponse.header)
}

// repeated .apollo.routing.RoadSegment road = 2;
inline int RoutingResponse::road_size() const {
  return road_.size();
}
inline void RoutingResponse::clear_road() {
  road_.Clear();
}
inline const ::apollo::routing::RoadSegment& RoutingResponse::road(int index) const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingResponse.road)
  return road_.Get(index);
}
inline ::apollo::routing::RoadSegment* RoutingResponse::mutable_road(int index) {
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingResponse.road)
  return road_.Mutable(index);
}
inline ::apollo::routing::RoadSegment* RoutingResponse::add_road() {
  // @@protoc_insertion_point(field_add:apollo.routing.RoutingResponse.road)
  return road_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::apollo::routing::RoadSegment >*
RoutingResponse::mutable_road() {
  // @@protoc_insertion_point(field_mutable_list:apollo.routing.RoutingResponse.road)
  return &road_;
}
inline const ::google::protobuf::RepeatedPtrField< ::apollo::routing::RoadSegment >&
RoutingResponse::road() const {
  // @@protoc_insertion_point(field_list:apollo.routing.RoutingResponse.road)
  return road_;
}

// optional .apollo.routing.Measurement measurement = 3;
inline bool RoutingResponse::has_measurement() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RoutingResponse::set_has_measurement() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RoutingResponse::clear_has_measurement() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RoutingResponse::clear_measurement() {
  if (measurement_ != NULL) measurement_->::apollo::routing::Measurement::Clear();
  clear_has_measurement();
}
inline const ::apollo::routing::Measurement& RoutingResponse::measurement() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingResponse.measurement)
  return measurement_ != NULL ? *measurement_ : *default_instance_->measurement_;
}
inline ::apollo::routing::Measurement* RoutingResponse::mutable_measurement() {
  set_has_measurement();
  if (measurement_ == NULL) {
    measurement_ = new ::apollo::routing::Measurement;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingResponse.measurement)
  return measurement_;
}
inline ::apollo::routing::Measurement* RoutingResponse::release_measurement() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingResponse.measurement)
  clear_has_measurement();
  ::apollo::routing::Measurement* temp = measurement_;
  measurement_ = NULL;
  return temp;
}
inline void RoutingResponse::set_allocated_measurement(::apollo::routing::Measurement* measurement) {
  delete measurement_;
  measurement_ = measurement;
  if (measurement) {
    set_has_measurement();
  } else {
    clear_has_measurement();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingResponse.measurement)
}

// optional .apollo.routing.RoutingRequest routing_request = 4;
inline bool RoutingResponse::has_routing_request() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RoutingResponse::set_has_routing_request() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RoutingResponse::clear_has_routing_request() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RoutingResponse::clear_routing_request() {
  if (routing_request_ != NULL) routing_request_->::apollo::routing::RoutingRequest::Clear();
  clear_has_routing_request();
}
inline const ::apollo::routing::RoutingRequest& RoutingResponse::routing_request() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingResponse.routing_request)
  return routing_request_ != NULL ? *routing_request_ : *default_instance_->routing_request_;
}
inline ::apollo::routing::RoutingRequest* RoutingResponse::mutable_routing_request() {
  set_has_routing_request();
  if (routing_request_ == NULL) {
    routing_request_ = new ::apollo::routing::RoutingRequest;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingResponse.routing_request)
  return routing_request_;
}
inline ::apollo::routing::RoutingRequest* RoutingResponse::release_routing_request() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingResponse.routing_request)
  clear_has_routing_request();
  ::apollo::routing::RoutingRequest* temp = routing_request_;
  routing_request_ = NULL;
  return temp;
}
inline void RoutingResponse::set_allocated_routing_request(::apollo::routing::RoutingRequest* routing_request) {
  delete routing_request_;
  routing_request_ = routing_request;
  if (routing_request) {
    set_has_routing_request();
  } else {
    clear_has_routing_request();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingResponse.routing_request)
}

// optional bytes map_version = 5;
inline bool RoutingResponse::has_map_version() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RoutingResponse::set_has_map_version() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RoutingResponse::clear_has_map_version() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RoutingResponse::clear_map_version() {
  map_version_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_map_version();
}
inline const ::std::string& RoutingResponse::map_version() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingResponse.map_version)
  return map_version_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoutingResponse::set_map_version(const ::std::string& value) {
  set_has_map_version();
  map_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:apollo.routing.RoutingResponse.map_version)
}
inline void RoutingResponse::set_map_version(const char* value) {
  set_has_map_version();
  map_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:apollo.routing.RoutingResponse.map_version)
}
inline void RoutingResponse::set_map_version(const void* value, size_t size) {
  set_has_map_version();
  map_version_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:apollo.routing.RoutingResponse.map_version)
}
inline ::std::string* RoutingResponse::mutable_map_version() {
  set_has_map_version();
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingResponse.map_version)
  return map_version_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* RoutingResponse::release_map_version() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingResponse.map_version)
  clear_has_map_version();
  return map_version_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void RoutingResponse::set_allocated_map_version(::std::string* map_version) {
  if (map_version != NULL) {
    set_has_map_version();
  } else {
    clear_has_map_version();
  }
  map_version_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), map_version);
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingResponse.map_version)
}

// optional .apollo.common.StatusPb status = 6;
inline bool RoutingResponse::has_status() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void RoutingResponse::set_has_status() {
  _has_bits_[0] |= 0x00000020u;
}
inline void RoutingResponse::clear_has_status() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void RoutingResponse::clear_status() {
  if (status_ != NULL) status_->::apollo::common::StatusPb::Clear();
  clear_has_status();
}
inline const ::apollo::common::StatusPb& RoutingResponse::status() const {
  // @@protoc_insertion_point(field_get:apollo.routing.RoutingResponse.status)
  return status_ != NULL ? *status_ : *default_instance_->status_;
}
inline ::apollo::common::StatusPb* RoutingResponse::mutable_status() {
  set_has_status();
  if (status_ == NULL) {
    status_ = new ::apollo::common::StatusPb;
  }
  // @@protoc_insertion_point(field_mutable:apollo.routing.RoutingResponse.status)
  return status_;
}
inline ::apollo::common::StatusPb* RoutingResponse::release_status() {
  // @@protoc_insertion_point(field_release:apollo.routing.RoutingResponse.status)
  clear_has_status();
  ::apollo::common::StatusPb* temp = status_;
  status_ = NULL;
  return temp;
}
inline void RoutingResponse::set_allocated_status(::apollo::common::StatusPb* status) {
  delete status_;
  status_ = status;
  if (status) {
    set_has_status();
  } else {
    clear_has_status();
  }
  // @@protoc_insertion_point(field_set_allocated:apollo.routing.RoutingResponse.status)
}

#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace routing
}  // namespace apollo

#ifndef SWIG
namespace google {
namespace protobuf {

template <> struct is_proto_enum< ::apollo::routing::ChangeLaneType> : ::google::protobuf::internal::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::apollo::routing::ChangeLaneType>() {
  return ::apollo::routing::ChangeLaneType_descriptor();
}

}  // namespace protobuf
}  // namespace google
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_modules_2frouting_2fproto_2frouting_2eproto__INCLUDED
