pipelines:
  default:
    - parallel:
      - step:
          name: Melodic
          image: ros:melodic
          script:
            - mkdir -p /tmp/src/repo && mv `pwd`/* /tmp/src/repo && mv /tmp/src `pwd`  # Move everything into the src directory
            - source `find /opt/ros -name setup.bash | sort | head -1` && echo $ROS_DISTRO # Source ROS environment
            - apt update && rosdep install --from-paths src --ignore-src -y # Install dependencies missing from the docker image
            - catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release
            - catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --make-args tests
            - catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --make-args run_tests -j1
            - for x in build_isolated/**/test_results; do cp -r $x/ .; done && mv test_results test-results # Create top level test-results folder for Pipelines
            - catkin_test_results build_isolated # Display test results and error on any test failure
      - step:
          name: Kinetic
          image: ros:kinetic
          script:
            - mkdir -p /tmp/src/repo && mv `pwd`/* /tmp/src/repo && mv /tmp/src `pwd`  # Move everything into the src directory
            - source `find /opt/ros -name setup.bash | sort | head -1` && echo $ROS_DISTRO # Source ROS environment
            - apt update && rosdep install --from-paths src --ignore-src -y # Install dependencies missing from the docker image
            - catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release
            - catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --make-args tests
            - catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --make-args run_tests -j1
            - for x in build_isolated/**/test_results; do cp -r $x/ .; done && mv test_results test-results # Create top level test-results folder for Pipelines
            - catkin_test_results build_isolated # Display test results and error on any test failure
      - step:
          name: Indigo
          image: ros:indigo
          script:
            - mkdir -p /tmp/src/repo && mv `pwd`/* /tmp/src/repo && mv /tmp/src `pwd`  # Move everything into the src directory
            - source `find /opt/ros -name setup.bash | sort | head -1` && echo $ROS_DISTRO # Source ROS environment
            - apt-get update && rosdep install --from-paths src --ignore-src -y # Install dependencies missing from the docker image
            - apt-get install build-essential -y # Indigo doesn't include the compiler for some reason...
            - catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release
            - catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --make-args tests
            - catkin_make_isolated --install -DCMAKE_BUILD_TYPE=Release --make-args run_tests -j1
            - for x in build_isolated/**/test_results; do cp -r $x/ .; done && mv test_results test-results # Create top level test-results folder for Pipelines
            - catkin_test_results build_isolated # Display test results and error on any test failure

